"""Code generation service (Sprint 13; Sprint 24 activation).

Generates the concrete file changes for a task. The *decision* of what to
generate comes from the implementation plan; the file content is produced
through the Provider Abstraction Layer (provider-independent).

Sprint 24 [P0-3]: file content is now produced by REAL provider execution
(e.g. Ollama). The previous deterministic template scaffold has been removed —
if the provider returns no parseable file content, generation FAILS rather than
falling back to a template (no fake success, no template execution).
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field

from sqlalchemy.orm import Session

from app.domain.development_enums import ChangeType
from app.providers import ExecutionRequest, Message


def slugify(title: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "_", title.lower()).strip("_")
    if not slug or slug[0].isdigit():
        slug = f"feature_{slug}" if slug else "feature"
    return slug[:40]


_LANG_BY_EXT = {
    "py": "python", "md": "markdown", "txt": "text", "json": "json",
    "ts": "typescript", "tsx": "typescript", "js": "javascript", "jsx": "javascript",
    "html": "html", "css": "css", "yml": "yaml", "yaml": "yaml", "sh": "shell",
    "toml": "toml", "cfg": "text", "ini": "text",
}


def _language_for(path: str) -> str:
    ext = path.rsplit(".", 1)[-1].lower() if "." in path else ""
    return _LANG_BY_EXT.get(ext, "text")


# A generated file block:  <<<FILE: path>>> \n <content> \n <<<END>>>
# Tolerant of 2+ closing '>' (small models sometimes emit '>>').
_FILE_RE = re.compile(
    r"<<<FILE:\s*(?P<path>.+?)>>+[ \t]*\n(?P<body>.*?)(?:\n<<<END>>+|\Z)", re.DOTALL
)


def _strip_thinking(text: str) -> str:
    """Remove qwen3/reasoning traces.

    Handles paired <think>...</think>, and the common qwen3 `/no_think` case where
    the opening tag is implicit but a closing </think> is present: everything up to
    and including the last </think> is reasoning and is dropped.
    """
    text = re.sub(r"<think>.*?</think>", "", text, flags=re.DOTALL)
    if "</think>" in text:
        text = text.rsplit("</think>", 1)[1]
    return text.strip()


def _strip_fences(content: str) -> str:
    content = re.sub(r"^```[a-zA-Z0-9_+-]*[ \t]*\n", "", content)
    content = re.sub(r"\n```[ \t]*$", "", content)
    return content


# Fallback extraction for when the model ignores the protocol and instead emits
# fenced code blocks with the path in a header line just above the fence, e.g.
#   **path/to/file.py**            |  File: path/to/file.py  |  # path/to/file.py
#   ```python
#   ...code...
#   ```
# This parses REAL generated code — it is not a template; unlabelled fences are
# skipped rather than invented.
_FENCE_BLOCK_RE = re.compile(
    r"```[a-zA-Z0-9_+-]*[ \t]*\n(?P<body>.*?)\n```", re.DOTALL
)
_PATH_HINT_RE = re.compile(
    r"(?:\*\*|`|#+\s|File:\s*|Filename:\s*|//\s*|#\s*)?"
    r"(?P<path>[\w./-]+\.[A-Za-z0-9]{1,6})"
)


def _parse_changes(text: str, provider_name: str, title: str) -> list["ProposedChange"]:
    """Extract file changes from a real provider response.

    Primary: the ``<<<FILE: …>>>`` protocol. Secondary: labelled fenced code
    blocks (path in the line above the fence). Both parse genuine model output;
    neither fabricates content.
    """
    changes: list[ProposedChange] = []
    for i, m in enumerate(_FILE_RE.finditer(text)):
        path = m.group("path").strip().strip('"').strip("`").lstrip("/")
        content = _strip_fences(m.group("body").strip("\n"))
        if not path:
            continue
        changes.append(
            ProposedChange(
                path=path, change_type=ChangeType.CREATE, content=content + "\n",
                language=_language_for(path),
                rationale=f"Generated by provider '{provider_name}' for: {title}",
                sequence=i,
            )
        )
    if changes:
        return changes
    # Secondary: labelled fenced blocks.
    seen: set[str] = set()
    for i, m in enumerate(_FENCE_BLOCK_RE.finditer(text)):
        prefix = text[max(0, m.start() - 120):m.start()].strip().splitlines()
        header = prefix[-1] if prefix else ""
        hint = _PATH_HINT_RE.search(header)
        if not hint:
            continue
        path = hint.group("path").strip().strip('"').strip("`").lstrip("/")
        body = m.group("body").strip("\n")
        if not path or path in seen or not body.strip():
            continue
        seen.add(path)
        changes.append(
            ProposedChange(
                path=path, change_type=ChangeType.CREATE, content=body + "\n",
                language=_language_for(path),
                rationale=f"Generated by provider '{provider_name}' for: {title}",
                sequence=i,
            )
        )
    return changes


@dataclass
class ProposedChange:
    path: str
    change_type: ChangeType
    content: str
    language: str
    rationale: str
    sequence: int = 0


@dataclass
class GenerationResult:
    changes: list[ProposedChange] = field(default_factory=list)
    slug: str = ""


class GenerationService:
    def __init__(self, db: Session):
        self.db = db

    def generate(
        self, title: str, description: str | None = None, provider_name: str | None = None,
        context: str = "",
    ) -> GenerationResult:
        """Produce file changes for a task using REAL provider execution.

        The provider is asked to emit one or more file blocks; each becomes a
        ProposedChange. No template fallback: an unparseable/empty response
        raises, failing the task honestly.

        Phase 5: ``context`` (repository + company-memory awareness) is injected so
        the code reuses existing modules/conventions rather than duplicating them.
        Backward compatible — omitted ⇒ identical behaviour.
        """
        from app.services.providers_service import ProviderService

        providers = ProviderService(self.db)
        row = (
            providers.get_by_name(provider_name)
            if provider_name
            else providers.default_provider()
        )
        if row is None:
            raise ValueError("No AI provider available for code generation")

        # Phase C: code generation routes through the Company Brain's orchestrator,
        # which selects the best coding provider and falls back automatically on
        # failure. The resolved row is a preference hint; behaviour with a single
        # enabled provider is identical to before.
        from app.services.provider_orchestrator import AIProviderOrchestrator

        orchestrator = AIProviderOrchestrator(self.db)
        instruction = (
            "You are an autonomous software engineer at WES. Implement the task by "
            "producing the COMPLETE file(s) required. Respond with ONLY file blocks in "
            "EXACTLY this format, one per file, and NOTHING else — no explanation, no "
            "commentary, no code fences:\n"
            "<<<FILE: relative/path.ext>>>\n"
            "<entire verbatim file content>\n"
            "<<<END>>>"
        )
        # `/no_think` (qwen3 soft switch) must lead the user turn to suppress the
        # inline reasoning trace on CPU-only inference.
        # Context goes FIRST and is capped; the format requirement is restated LAST
        # so the final instruction the model sees is "emit file blocks" (recency).
        # Putting context last made the model answer the context in prose instead.
        ctx = f"Repository & company context (for reuse):\n{context[:700]}\n\n" if context else ""
        user = (
            f"/no_think\n{ctx}"
            f"Task: {title}\nDetails: {description or title}\n\n"
            "Now output ONLY the file blocks (<<<FILE: path>>> ... <<<END>>>). "
            "No explanation, no analysis, no prose."
        )
        result, _used = orchestrator.execute(
            ExecutionRequest(
                messages=[Message("system", instruction), Message("user", user)],
                metadata={"role": "Backend Engineer", "task": title},
            ),
            task_type="coding", prefer=row.name,
        )
        text = _strip_thinking(result.output or "")
        changes = _parse_changes(text, row.name, title)

        # Real retry (NOT a fallback): small local models occasionally answer in
        # prose instead of the file-block protocol. Re-ask ONCE with a firmer,
        # example-led instruction. Still 100% real provider output — no template.
        if not changes:
            retry_user = (
                "/no_think\n"
                "Your previous answer contained no file blocks. Output NOTHING but "
                "file blocks in EXACTLY this format — no prose, no analysis, no fences:\n"
                "<<<FILE: path/to/file.ext>>>\n<full file content>\n<<<END>>>\n\n"
                f"Task: {title}\nDetails: {description or title}"
            )
            retry, _u = orchestrator.execute(
                ExecutionRequest(
                    messages=[Message("system", instruction), Message("user", retry_user)],
                    metadata={"role": "Backend Engineer", "task": title, "format": "fileblocks"},
                ),
                task_type="coding", prefer=row.name,
            )
            changes = _parse_changes(_strip_thinking(retry.output or ""), row.name, title)

        if not changes:
            raise ValueError(
                f"Provider '{row.name}' returned no parseable file content "
                f"(response length={len(text)}). Refusing to emit a template scaffold."
            )
        return GenerationResult(slug=slugify(title), changes=changes)
