"""Mock provider — a fully functional, deterministic provider for testing.

Requires no API keys. Produces a structured, role-aware response so the entire
orchestration pipeline can run end-to-end without any external service.

Code generation: when asked to implement a task (the request carries the
``<<<FILE: …>>>`` file-block protocol used by ``dev_generation``), the mock emits
a real, compilable module + a passing test + implementation notes in that exact
protocol. This keeps ``dev_generation`` free of any template (Sprint 24 removed
the production scaffold on purpose) while still letting the offline test suite
verify the full modify → compile → test → review → git → PR pipeline the
Blueprint requires (Vol 04 / Vol 08). A real provider (e.g. Ollama) supplies
richer content through the identical protocol, with no code change.
"""

from __future__ import annotations

import re
import time
from collections.abc import Iterator

from app.providers.base import (
    BaseProvider,
    ExecutionRequest,
    ExecutionResult,
    ProviderHealth,
)


def _slug(title: str) -> str:
    s = re.sub(r"[^a-z0-9]+", "_", (title or "").lower()).strip("_")
    if not s or s[0].isdigit():
        s = f"feature_{s}" if s else "feature"
    return s[:40]


class MockProvider(BaseProvider):
    name = "mock"
    default_model = "mock-1"
    cost_per_1k_input = 0.0
    cost_per_1k_output = 0.0

    def initialize(self) -> None:
        self._initialized = True

    def health(self) -> ProviderHealth:
        return ProviderHealth(status="healthy", detail="Mock provider is always available.")

    def test_connection(self) -> dict:
        return {
            "ok": True,
            "status": "healthy",
            "detail": "Mock provider is always reachable.",
            "model": self.default_model,
            "version": "mock",
            "latency_ms": 1,
        }

    def _is_codegen(self, request: ExecutionRequest) -> bool:
        """A code-generation request carries the file-block protocol marker."""
        return "<<<FILE:" in request.as_text()

    def _codegen(self, request: ExecutionRequest) -> str:
        """Emit a compilable module + passing test + notes in the file-block protocol.

        Mirrors the contract ``dev_generation`` expects: ≥1 file block, valid
        Python, a ``test_`` file, and a markdown notes file. The module and test
        are self-consistent so the sandbox test run genuinely passes.
        """
        title = request.metadata.get("task") or "the assigned task"
        slug = _slug(title)
        func = slug if slug.isidentifier() else "run"
        safe_title = title.replace('"', "'")

        module = (
            f'"""{safe_title}.\n\n'
            "Autonomously generated by the WES Development Engine.\n"
            '"""\n\n'
            "from __future__ import annotations\n\n"
            f'FEATURE = "{slug}"\n\n\n'
            f"def {func}() -> dict:\n"
            '    """Return a structured description of this feature."""\n'
            f'    return {{"feature": FEATURE, "title": "{safe_title}", "status": "implemented"}}\n\n\n'
            "def is_ready() -> bool:\n"
            '    """Return True when the feature is ready for review."""\n'
            f'    return {func}()["status"] == "implemented"\n'
        )
        test = (
            f'"""Tests for the autonomously generated `{slug}` feature."""\n\n'
            f"from {slug} import {func}, is_ready\n\n\n"
            f"def test_{func}_returns_structure():\n"
            f"    result = {func}()\n"
            f'    assert result["feature"] == "{slug}"\n'
            f'    assert result["status"] == "implemented"\n\n\n'
            "def test_is_ready():\n"
            "    assert is_ready() is True\n"
        )
        notes = (
            f"# Implementation Notes — {safe_title}\n\n"
            "Autonomously generated by the WES Development Engine.\n\n"
            "## Files\n"
            f"- `{slug}.py` — feature module (documented, typed)\n"
            f"- `test_{slug}.py` — unit tests (passing)\n\n"
            "## Verification\n"
            f"- `python -m py_compile {slug}.py`\n"
            "- `python -m pytest`\n"
        )
        return (
            f"<<<FILE: {slug}.py>>>\n{module}<<<END>>>\n"
            f"<<<FILE: test_{slug}.py>>>\n{test}<<<END>>>\n"
            f"<<<FILE: NOTES_{slug}.md>>>\n{notes}<<<END>>>\n"
        )

    def _respond(self, request: ExecutionRequest) -> str:
        if self._is_codegen(request):
            return self._codegen(request)
        role = request.metadata.get("role", "AI Employee")
        task = request.metadata.get("task", "the assigned task")
        return (
            f"[mock:{self.model_name(request)}] As the {role}, I have completed {task}. "
            "Output follows the SOP and meets the acceptance criteria. "
            "Ready for review and handoff to the next stage."
        )

    def model_name(self, request: ExecutionRequest) -> str:
        return request.model or self.default_model

    def execute(self, request: ExecutionRequest) -> ExecutionResult:
        start = time.perf_counter()
        prompt_tokens = self.estimate_tokens(request.as_text())
        output = self._respond(request)
        completion_tokens = self.estimate_tokens(output)
        latency_ms = int((time.perf_counter() - start) * 1000) + 5  # deterministic-ish
        total = prompt_tokens + completion_tokens
        return ExecutionResult(
            output=output,
            provider=self.name,
            model=self.model_name(request),
            prompt_tokens=prompt_tokens,
            completion_tokens=completion_tokens,
            total_tokens=total,
            cost=self.estimate_cost(prompt_tokens, completion_tokens),
            currency="USD",
            latency_ms=latency_ms,
            status="completed",
        )

    def stream(self, request: ExecutionRequest) -> Iterator[str]:
        for word in self._respond(request).split():
            yield word + " "

    def cancel(self, run_id: str) -> bool:
        return True
